services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DOCKERDATA:/config
    labels:
      - "traefik.enable=true"   
      # web
      - "traefik.http.routers.overseerr-rtr.rule=Host(`request.$DOMAINNAME`)"
      - "traefik.http.routers.overseerr-rtr.entrypoints=websecure"
      - "traefik.http.routers.overseerr-rtr.service=overseerr-svc"
      - "traefik.http.services.overseerr-svc.loadbalancer.server.port=5055"
      
networks:
  default:
    external: true
    name: myNetwork
