services:
  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr
    restart: unless-stopped
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DOCKERDATA:/config
    labels:
      - "traefik.enable=true"   
      # web
      - "traefik.http.routers.seerr-rtr.rule=Host(`request.$DOMAINNAME`)"
      - "traefik.http.routers.seerr-rtr.entrypoints=websecure"
      - "traefik.http.routers.seerr-rtr.service=seerr-svc"
      - "traefik.http.services.seerr-svc.loadbalancer.server.port=5055"
      
networks:
  default:
    external: true
    name: myNetwork
