[[repo]]
name = "homelab"
[repo.config]
server = "mgr"
builder = "Local"
git_account = "gsmetana"
repo = "gsmetana/homelab"

[[resource_sync]]
name = "homelab"
[resource_sync.config]
linked_repo = "homelab"
resource_path = ["main.toml"]
managed = true

[[server]]
name = "mgr"
[server.config]
enabled = true

[[server]]
name = "nas"
[server.config]
address = "https://periphery-nas:8120"
enabled = true

[[builder]]
name = "Local"
[builder.config]
type = "Server"
params.server_id = "mgr"

[[procedure]]
name = "Backup Core Database"
description = "Triggers the Core database backup at the scheduled time."
tags = ["system"]
config.schedule = "Every day at 01:00"

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [
  { execution.type = "BackupCoreDatabase", execution.params = {}, enabled = true }
]

[[procedure]]
name = "Global Auto Update"
description = "Pulls and auto updates Stacks and Deployments using 'poll_for_updates' or 'auto_update'."
tags = ["system"]
config.schedule = "Every day at 03:00"

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [
  { execution.type = "GlobalAutoUpdate", execution.params = {}, enabled = true }
]