[[server]]
name = "mgr"
[server.config]
address = "https://192.168.0.85:8120"
enabled = true

##

[[server]]
name = "nas"
[server.config]
address = "https://192.168.0.13:8120"
enabled = true

##


[[deployment]]
name = "terraforming-mars"
[deployment.config]
server = "mgr"
image.type = "Build"
image.params.build = "terraforming-mars"
network = "myNetwork"
restart = "unless-stopped"
environment = """
  
"""
labels = """
- "traefik.enable=true"     
# web      
- "traefik.http.routers.mars-https.rule=Host(\`mars.[[DOMAINNAME]]\`)"
- "traefik.http.routers.mars-https.entrypoints=websecure"
- "traefik.http.routers.mars-https.service=mars-https"
- "traefik.http.services.mars-https.loadbalancer.server.port=8080"
"""

##

[[build]]
name = "terraforming-mars"
[build.config]
builder = "Local"
linked_repo = "terraforming-mars"

##

[[repo]]
name = "homelab"
[repo.config]
server = "mgr"
builder = "Local"
git_account = "gsmetana"
repo = "gsmetana/homelab"

##

[[repo]]
name = "terraforming-mars"
[repo.config]
server = "nas"
builder = "Local"
git_account = "gsmetana"
repo = "terraforming-mars/terraforming-mars"

##

[[procedure]]
name = "Backup Core Database"
description = "Triggers the Core database backup at the scheduled time."
tags = ["system"]
config.schedule = "Every day at 01:00"

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [
  { execution.type = "BackupCoreDatabase", execution.params = {}, enabled = true }
]

##

[[procedure]]
name = "Global Auto Update"
description = "Pulls and auto updates Stacks and Deployments using 'poll_for_updates' or 'auto_update'."
tags = ["system"]
config.schedule = "Every day at 03:00"

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [
  { execution.type = "GlobalAutoUpdate", execution.params.skip_auto_update = false, enabled = true }
]

##

[[procedure]]
name = "Rotate Server Keys"
description = "Rotates all currently connected Server keys."
tags = ["system"]
config.schedule = "Every day at 06:00"

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [
  { execution.type = "RotateAllServerKeys", execution.params = {}, enabled = true }
]

##

[[builder]]
name = "Local"
[builder.config]
type = "Server"
params.servers = ["mgr"]

##

[[resource_sync]]
name = "main"
[resource_sync.config]
linked_repo = "homelab"
resource_path = ["main.toml"]
managed = true

##

[[resource_sync]]
name = "stacks"
[resource_sync.config]
linked_repo = "homelab"
resource_path = ["stacks.toml"]
managed = true