[[stack]]
name = "tautulli"
[stack.config]
server = "nas"
linked_repo = "homelab"
run_directory = "tautulli"
environment = """
DOMAINNAME=[[DOMAINNAME]]
TZ=[[TZ]]
PUID=[[PUID]]
PGID=[[PGID]]
CONFIGROOT=[[CONFIGROOT]]
"""

[[stack]]
name = "termix"
[stack.config]
server = "mgr"
linked_repo = "homelab"
run_directory = "termix"
environment = """
DOMAINNAME=[[DOMAINNAME]]
"""

[[stack]]
name = "prowlarr"
[stack.config]
server = "nas"
linked_repo = "homelab"
run_directory = "prowlarr"
environment = """
DOMAINNAME=[[DOMAINNAME]]
TZ=[[TZ]]
PUID=[[PUID]]
PGID=[[PGID]]
CONFIGROOT=[[CONFIGROOT]]
"""

[[stack]]
name = "omada"
description = "I don't think traefik reverse proxy is working for this... may need to access at <mgr ip>:8043"
[stack.config]
server = "mgr"
linked_repo = "homelab"
run_directory = "omada"
environment = """
DOMAINNAME=[[DOMAINNAME]]
DOCKERDATA_MGR=[[DOCKERDATA_MGR]]
"""

[[stack]]
name = "sonarr"
[stack.config]
server = "nas"
linked_repo = "homelab"
run_directory = "sonarr"
environment = """
DOMAINNAME=[[DOMAINNAME]]
TZ=[[TZ]]
PUID=[[PUID]]
PGID=[[PGID]]
CONFIGROOT=[[CONFIGROOT]]
MEDIAROOT=[[MEDIAROOT]]
"""

[[stack]]
name = "lidarr"
[stack.config]
server = "nas"
linked_repo = "homelab"
run_directory = "lidarr"
environment = """
DOMAINNAME=[[DOMAINNAME]]
TZ=[[TZ]]
PUID=[[PUID]]
PGID=[[PGID]]
CONFIGROOT=[[CONFIGROOT]]
MEDIAROOT=[[MEDIAROOT]]
"""

[[stack]]
name = "qbittorrent"
[stack.config]
server = "nas"
linked_repo = "homelab"
run_directory = "qbittorrent"
environment = """
DOMAINNAME=[[DOMAINNAME]]
TZ=[[TZ]]
PUID=[[PUID]]
PGID=[[PGID]]
CONFIGROOT=[[CONFIGROOT]]
MEDIAROOT=[[MEDIAROOT]]

GSP_GTN_API_KEY=[[GSP_GTN_API_KEY]]
"""

[[stack]]
name = "qui"
[stack.config]
server = "nas"
linked_repo = "homelab"
run_directory = "qui"
environment = """
DOMAINNAME=[[DOMAINNAME]]
TZ=[[TZ]]
PUID=[[PUID]]
PGID=[[PGID]]
CONFIGROOT=[[CONFIGROOT]]
MEDIAROOT=[[MEDIAROOT]]
"""

[[stack]]
name = "firefox"
[stack.config]
server = "nas"
linked_repo = "homelab"
run_directory = "firefox"
environment = """
DOMAINNAME=[[DOMAINNAME]]
TZ=[[TZ]]
PUID=[[PUID]]
PGID=[[PGID]]
CONFIGROOT=[[CONFIGROOT]]
"""

[[stack]]
name = "lsa-raid"
[stack.config]
server = "nas"
linked_repo = "homelab"
run_directory = "lsa-raid"
environment = """
DOMAINNAME=[[DOMAINNAME]]
TZ=[[TZ]]
CONFIGROOT=[[CONFIGROOT]]
LSA_ROOT_PASSWORD=[[LSA_ROOT_PASSWORD]]
"""

[[stack]]
name = "lounge"
[stack.config]
server = "nas"
linked_repo = "homelab"
run_directory = "lounge"
environment = """
DOMAINNAME=[[DOMAINNAME]]
TZ=[[TZ]]
PUID=[[PUID]]
PGID=[[PGID]]
CONFIGROOT=[[CONFIGROOT]]
"""

[[stack]]
name = "overseerr"
[stack.config]
server = "nas"
linked_repo = "homelab"
run_directory = "overseerr"
environment = """
DOMAINNAME=[[DOMAINNAME]]
TZ=[[TZ]]
PUID=[[PUID]]
PGID=[[PGID]]
CONFIGROOT=[[CONFIGROOT]]
"""

[[stack]]
name = "cloudflared"
[stack.config]
server = "mgr"
linked_repo = "homelab"
run_directory = "cloudflared"
environment = """
TUNNEL_TOKEN=[[CF_TUNNEL_TOKEN]]
"""

[[stack]]
name = "radarr"
[stack.config]
server = "nas"
linked_repo = "homelab"
run_directory = "radarr"
environment = """
DOMAINNAME=[[DOMAINNAME]]
TZ=[[TZ]]
PUID=[[PUID]]
PGID=[[PGID]]
CONFIGROOT=[[CONFIGROOT]]
MEDIAROOT=[[MEDIAROOT]]
"""

[[stack]]
name = "plex"
[stack.config]
server = "nas"
linked_repo = "homelab"
run_directory = "plex"
environment = """
DOMAINNAME=[[DOMAINNAME]]
TZ=[[TZ]]
PUID=[[PUID]]
PGID=[[PGID]]
CONFIGROOT=[[CONFIGROOT]]
MEDIAROOT=[[MEDIAROOT]]
"""

[[stack]]
name = "traefik-kop-nas"
[stack.config]
server = "nas"
linked_repo = "homelab"
run_directory = "traefik-kop-nas"
environment = """
DOMAINNAME=[[DOMAINNAME]]
"""

[[stack]]
name = "jackett"
[stack.config]
server = "nas"
linked_repo = "homelab"
run_directory = "jackett"
environment = """
DOMAINNAME=[[DOMAINNAME]]
TZ=[[TZ]]
PUID=[[PUID]]
PGID=[[PGID]]
CONFIGROOT=[[CONFIGROOT]]
MEDIAROOT=[[MEDIAROOT]]
"""

[[stack]]
name = "vaultwarden"
[stack.config]
server = "mgr"
linked_repo = "homelab"
run_directory = "vaultwarden"
environment = """
DOMAINNAME=[[DOMAINNAME]]
EMAIL_HOST=[[EMAIL_HOST]]
EMAIL_FROM=[[EMAIL_FROM]]
"""

[[stack]]
name = "postfix"
[stack.config]
server = "mgr"
linked_repo = "homelab"
run_directory = "postfix"
environment = """
TZ=[[TZ]]
RELAY_USER=[[RELAY_USER]]
RELAY_PASS=[[RELAY_PASS]]
TEST_EMAIL=[[TEST_EMAIL]]
EMAIL_FROM=[[EMAIL_FROM]]
DOMAINNAME=[[DOMAINNAME]]
"""

[[stack]]
name = "bazarr"
[stack.config]
server = "nas"
linked_repo = "homelab"
run_directory = "bazarr"
environment = """
DOMAINNAME=[[DOMAINNAME]]
TZ=[[TZ]]
PUID=[[PUID]]
PGID=[[PGID]]
CONFIGROOT=[[CONFIGROOT]]
MEDIAROOT=[[MEDIAROOT]]
"""

[[stack]]
name = "gluetun"
[stack.config]
server = "nas"
linked_repo = "homelab"
run_directory = "gluetun"
pre_deploy.command = """
GSP_GTN_API_KEY=[[GSP_GTN_API_KEY]]

echo '[[roles]]' > config.toml
echo 'name = "t-anc/GSP-Qbittorent-Gluetun-sync-port-mod"' >> config.toml
echo 'routes = ["GET /v1/portforward"]' >> config.toml
echo 'auth = "apikey"' >> config.toml
echo 'apikey = "'$GSP_GTN_API_KEY'"' >> config.toml
"""
environment = """
DOMAINNAME=[[DOMAINNAME]]
TZ=[[TZ]]
PUID=[[PUID]]
PGID=[[PGID]]
CONFIGROOT=[[CONFIGROOT]]
MEDIAROOT=[[MEDIAROOT]]

WIREGUARD_PRIVATE_KEY=[[WIREGUARD_PRIVATE_KEY]]
"""

[[stack]]
name = "traefik"
[stack.config]
server = "mgr"
linked_repo = "homelab"
run_directory = "traefik"
environment = """
DOMAINNAME=[[DOMAINNAME]]
CLOUDFLARE_DNS_API_TOKEN=[[CLOUDFLARE_DNS_API_TOKEN]]
CLOUDFLARE_EMAIL=[[CLOUDFLARE_EMAIL]]
DOCKERDATA_MGR=[[DOCKERDATA_MGR]]
"""

[[stack]]
name = "authentik"
[stack.config]
server = "mgr"
linked_repo = "homelab"
run_directory = "authentik"
environment = """
AUTHENTIK_POSTGRESQL_PASSWORD=[[AUTHENTIK_POSTGRESQL_PASSWORD]]
AUTHENTIK_SECRET_KEY=[[AUTHENTIK_SECRET_KEY]]
DOMAINNAME=[[DOMAINNAME]]
EMAIL_HOST=[[EMAIL_HOST]]
EMAIL_FROM=[[EMAIL_FROM]]

DOCKERDATA_MGR=[[DOCKERDATA_MGR]]
"""

[[stack]]
name = "proxbackup-nas"
[stack.config]
server = "nas"
linked_repo = "homelab"
run_directory = "proxbackup-nas"
environment = """
TZ=[[TZ]]
CONFIGROOT=[[CONFIGROOT]]
RAIDROOT=[[RAIDROOT]]
PBS_ENDPOINT=[[PBS_ENDPOINT]]
PBS_DATASTORE=[[PBS_DATASTORE]]
PBS_API_KEY_NAME=[[PBS_API_KEY_NAME]]
PBS_API_KEY_SECRET=[[PBS_API_KEY_SECRET]]
PBS_FINGERPRINT=[[PBS_FINGERPRINT]]

TS_AUTHKEY=[[TS_AUTHKEY]]
"""