services:
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/linuxserver/prowlarr:develop
    restart: unless-stopped
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $CONFIGROOT/prowlarr:/config
    labels:
      - "traefik.enable=true"   
      # web      
      - "traefik.http.routers.prowlarr-https.rule=Host(`prowlarr.$DOMAINNAME`)"
      - "traefik.http.routers.prowlarr-https.entrypoints=websecure"
      - "traefik.http.routers.prowlarr-https.service=prowlarr-https"
      - "traefik.http.services.prowlarr-https.loadbalancer.server.port=9696"

networks:
  default:
    external: true
    name: myNetwork
